import type { Metadata } from "next";
import { Geist, Geist_Mono,Montserrat } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"
import { Main, NextScript } from "next/document";
import Script from "next/script";
import {GoogleAnalytics} from '@next/third-parties/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets:['latin'],
  preload:true
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Fresh Flow Mobile Auto Spa</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased w-full`}
      >
         <GoogleAnalytics gaId="AW-16936450849" />
        {children}
      </body>
    </html>
  );
}
